add support for coconut (functional python) kernel
jupyter-vim/jupyter-vim pull request #102
Opened 2023-02-04 19:19 UTC by kksgandhi

2023-02-04 19:22 UTC, kksgandhi commented
This references issue #100

2023-02-04 19:22 UTC, kksgandhi commented
It seems like the REPL for coconut is exactly the same as python, so I was able to copy over the python language class to serve as the coconut language class in `python3/language.py`

2023-02-04 19:23 UTC, kksgandhi commented
For the coconut filetype plugin, I just copied the python filetype plugin. If there's a more intelligent way to handle this (e.g. something like `source ../python/jupyter.vim`) then I'm all ears.

2023-02-06 08:52 UTC, wmvanvliet commented
You can do `runtime! <sfile>:h/../julia/*.vim`. This command will source all the vim files in a path relative to the current file.

2023-02-06 08:53 UTC, wmvanvliet commented
See also https://vi.stackexchange.com/questions/3177/use-single-ftplugin-for-more-than-one-filetype

2023-02-10 02:43 UTC, kksgandhi commented
Thanks @wmvanvliet, made those changes!

2023-02-10 07:52 UTC, wmvanvliet requested changes

2023-02-10 07:52 UTC, wmvanvliet commented on ftplugin/coconut/jupyter.vim
> +runtime! ftplugin/python/jupyter.vim
As I understand it, `runtime` searches all the folders in the runtime path. So if a user has their own `.vim/ftplugin/python/jupyter.vim` file somewhere, that will get sourced too.

2023-02-10 07:54 UTC, wmvanvliet commented on ftplugin/coconut/jupyter.vim
> +runtime! ftplugin/python/jupyter.vim
So I do think we want to use a relative path here:

```suggestion
runtime! <sfile>:h/../python/jupyter.vim
```

2023-02-13 08:25 UTC, wmvanvliet commented
Works great. Thanks a lot @kksgandhi!

2023-02-13 08:26 UTC, wmvanvliet approved these changes

2023-02-13 08:26 UTC, merged

2023-02-14 00:44 UTC, kksgandhi commented
Thank you so much!